Finished clustering mini project (18)
JCardenasRdz/SpringBoard pull request #3
Opened 2017-03-13 00:48 UTC by JCardenasRdz

@amirziai,

I finished mini project 18.
The elbow method for Kmeans works great if I use OneHot encoding.

2017-03-14 02:00 UTC, amirziai requested changes
What is the number of clusters with highest average silhouette score?

2017-03-14 02:00 UTC, amirziai commented on Projects/18_Clustering/18_Exercise_Set_VI.py
> +import sklearn.cluster as skc
Try to use descriptive names or stick to the commonly used convention. `pd` and `np` are ok because they're always used but `skc` would throw other python programmers off for a sec, even if you come back to this in a months you probably have to think a bit before you realize what `skc` is.

2017-03-14 02:00 UTC, amirziai commented on Projects/18_Clustering/18_Exercise_Set_VI.py
> +def elbow_OneHot():
http://stackoverflow.com/questions/159720/what-is-the-naming-convention-in-python-for-variable-and-function-names

2017-03-14 02:00 UTC, amirziai commented on Projects/18_Clustering/18_Exercise_Set_VI.py
> +    for idx,K in enumerate(myK):
space

2017-03-14 02:00 UTC, amirziai commented on Projects/18_Clustering/18_Exercise_Set_VI.py
> +    plt.plot(myK,inertia,'-o'); plt.xlabel('Clusters');plt.ylabel('Inertia');
your code would be more readable if you have one statement per line http://docs.python-guide.org/en/latest/writing/style/#one-statement-per-line

2017-03-14 02:00 UTC, amirziai commented on Projects/18_Clustering/18_Exercise_Set_VI.py
> +    plt.figure(100,(5,5))
spaces

2017-03-17 14:00 UTC, JCardenasRdz commented on Projects/18_Clustering/18_Exercise_Set_VI.py
> +import sklearn.cluster as skc
@amirziai, what is the convention for sklearn ?

2017-03-17 16:47 UTC, JCardenasRdz reviewed
I updated the code and some spacing.

2017-03-17 16:47 UTC, JCardenasRdz commented on Projects/18_Clustering/silhouette.py
> +def mean_silhouette_scores(Xdata,range):
@amirziai 
I added this function to estimate the mean silhouette scores. The best number of clusters is 3.

2017-03-17 16:47 UTC, JCardenasRdz commented on Projects/18_Clustering/18_Exercise_Set_VI.py
> +    for idx,K in enumerate(myK):
done

2017-03-17 16:47 UTC, JCardenasRdz commented
done

2017-03-17 17:35 UTC, amirziai approved these changes

2017-03-17 17:35 UTC, amirziai commented on Projects/18_Clustering/18_Exercise_Set_VI.py
> +import sklearn.cluster as skc
There's no convention for `sklearn` as far as I know.

2017-03-17 22:12 UTC, merged